name: Install Angular dependencies

on:
  push:
    branches:
      - dev*
  pull_request:
   branches:
      - main
  

jobs:
  Install-and-Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install Node dependencies
      run: npm install --prefix ./frontend/
      
    - name: Build
      run: ng build frontend
