name: Install Angular dependencies

on:
  push:
    branches:
      - dev*
  pull_request:
   branches:
      - main
  

jobs:
  Install-and-Build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./Frontend
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - run: cd Frontend

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install Node dependencies
      run: npm install @angular/cli
      working-directory: ${{env.working-directory}} 
      
    - name: Install Angular dependencies
      run: npm install @angular/cli
      working-directory: ${{env.working-directory}} 
      
    - name: Build
      run: npm run build Frontend
      working-directory: ${{env.working-directory}} 
