name: Build and Test backend
# triggers
on:
  push:
    branches:
      - main 
      - dev*
  pull_request:
    branches:
      - main
      - dev*
# setup
jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
    
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
    
      - name: Cache the nuget
        id: nuget-cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.assets.json') }}
          restore-keys: ${{ runner.os }}-nuget

      - name: restore dependencies
        if: steps.nuget-cache.outputs.cache-hit != 'true'
        run: dotnet restore Backend/

      - name: Build
        run: dotnet build Backend/

      - name: Test
        run: dotnet test Backend/ --no-build