name: Build and Test backend

# triggers
on:
  push:
    branches: 
      - dev*
  pull_request:
    branches:
      - main

# setup
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6
      - name: Install dependencies
        run: dotnet restore Backend/
      - name: Build
        run: dotnet build Backend/ --configuration Release --no-restore
      - name: Test
        run: dotnet test Backend/ --no-build
    
